package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type structInfo struct {
	Name   string
	Fields []*ast.Field
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	err = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			if d.Name() == "vendor" || path == filepath.Join(root, "cmd", "reset") {
				return filepath.SkipDir
			}
		}

		if !d.IsDir() {
			return nil
		}

		processDir(path)
		return nil
	})

	if err != nil {
		panic(err)
	}
}

func processDir(dir string) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return
	}

	for _, pkg := range pkgs {
		var structs []structInfo

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}

				if !hasResetComment(gen.Doc) {
					continue
				}

				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					structs = append(structs, structInfo{
						Name:   ts.Name.Name,
						Fields: st.Fields.List,
					})
				}
			}
		}

		if len(structs) > 0 {
			generateResetFile(dir, pkg.Name, structs)
		}
	}
}

func hasResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func generateResetFile(dir, pkgName string, structs []structInfo) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by reset generator. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	for _, s := range structs {
		buf.WriteString(generateResetMethod(s))
		buf.WriteString("\n")
	}

	path := filepath.Join(dir, "reset.gen.go")
	_ = os.WriteFile(path, buf.Bytes(), 0644)
}

func generateResetMethod(s structInfo) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", s.Name))

	for _, field := range s.Fields {
		for _, name := range field.Names {
			buf.WriteString(generateFieldReset(name.Name, field.Type))
		}
	}

	buf.WriteString("}\n")
	return buf.String()
}

func generateFieldReset(fieldName string, expr ast.Expr) string {
	switch t := expr.(type) {

	case *ast.Ident:
		if isPrimitive(t.Name) {
			return fmt.Sprintf("\ts.%s = %s\n", fieldName, zeroValue(t.Name))
		}
		return fmt.Sprintf("\ts.%s.Reset()\n", fieldName)

	case *ast.ArrayType:
		return fmt.Sprintf("\ts.%s = s.%s[:0]\n", fieldName, fieldName)

	case *ast.MapType:
		return fmt.Sprintf("\tclear(s.%s)\n", fieldName)

	case *ast.StarExpr:
		return fmt.Sprintf(
			"\tif s.%s != nil {\n\t\ts.%s.Reset()\n\t}\n",
			fieldName, fieldName,
		)
	}

	return ""
}

func isPrimitive(t string) bool {
	switch t {
	case "int", "int64", "int32", "uint", "uint64", "float64", "float32",
		"string", "bool", "byte", "rune":
		return true
	}
	return false
}

func zeroValue(t string) string {
	switch t {
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		return "0"
	}
}
